### ISSUE TITLE
Improve title

### ISSUE THREAD

**Issue by silopolis** [nextcloud/files_confidential#17]
This could be improved for less ambiguity/better clarity by being more specific.
Plus, it becomes even more foggy when translated! :/

https://github.com/nextcloud/files_confidential/blob/master/src/views/Admin.vue#L11

**Comment by marcelklehr** [comment]
I didn't make that up, sadly. Business Authorization Framework is a proper name for a specification by the TSCP: https://pdfslide.net/documents/business-authorization-framework-version-1-baf-v1-business-authorization-framework.html?page=1

**Comment by silopolis** [comment]
Oh, OK, sorry.
Well, as LibreOffice doesn't translate it (https://help.libreoffice.org/7.4/fr/text/shared/guide/classification.html) I believe we shouldn't either…
Thank you for your support
Cheers!
